[hg_branch]
disabled=true

[docker_context]
only_with_files = true
detect_files =  ["docker-compose.machine.yml", "docker-compose.machine.override.yml", "Dockerfile"]

[directory]
truncate_to_repo = true

[directory.substitutions]
"/Volumes/hermes/projects" = "~/projects"

[gcloud]
disabled=true

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
