[hg_branch]
disabled=true

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[docker_context]
only_with_files = false
disabled = false

[directory]
truncate_to_repo = true

[directory.substitutions]
"/Volumes/hermes/projects" = "~/projects"
